# Accessing Servers {#access-server}

Created on 2020 Aug 25 by Gregory Stewart.

Ported to bookdown on 2022 Jul 26 by Nathan Muncy.

## LaBar Lab Shared Drive (keoki)

1. Request LaBar lab whitelist permissions from the lab manager 
(can sometimes take 24 hours for the update to push through).
2. Map the network drive
    + For Windows, go to `My computer` or `This PC` and map network drive. 
    Choose a drive and enter `\\ccn-keoki.win.duke.edu\experiments2\` to access 
    the lab's shared drive. Keep in mind that this is mapped to the specific PC 
    you are using, so will need to remap it to other computers as needed.
    + For Mac OSx, open `Finder` and select `go`. Select `connect to server` 
    and enter `smb://ccn-keoki.win.duke.edu/experiments2/` to access the lab's 
    shared drive. Keep in mind that this is mapped to the specific PC you are 
    using, so will need to remap it to other computers as needed.

## BIAC Servers

This document contains information on installing and setting up the local 
software necessary to log into and transfer files to/from the BIAC servers. 
This is required in order to access any imaging data collected at BIAC. 
Remotely logging into the BIAC servers will also allow you to run scripts on 
the servers and use the various image analysis software packages installed there.

**NOTE 1**: BIAC recently (11/2015) began requiring Duke’s multi-factor 
authentication system in order to log into their servers. If you have not set 
this up already, see this 
[web page](https://oit.duke.edu/net-security/security/multi-factor-authentication.php) 
for details.

**NOTE 2**: You will need a DHE account to fully log into the BIAC servers.

### Mac OSx Users

Mac OSX comes with the software necessary to log into and transfer files from 
the BIAC servers; no additional installation is required.

#### Logging into the BIAC Servers

1. Open a Terminal window. The Terminal application can be found in 
  `…/Applications/Utilities`.
2. Type `ssh -o ServerAliveInterval=120 -o TCPKeepAlive=no -X <username>@hugin.biac.duke.edu` 
  (replacing “username” with your actual user name) into the Terminal window. 
  After typing in your password when prompted and completing multi-factor 
  authentication you will be logged into the BIAC servers. If you are presented 
  with an “are you sure you want to connect” question, just type “yes”.
  
#### Copying Files from the BIAC Servers

1. Open a Terminal window. The Terminal application can be found in 
  `…/Applications/Utilities`.
2. Use the `scp` command to copy files between the BIAC servers and your 
  local computer.

#### Examples

Copy from BIAC to local:

`scp <username>@hugin.biac.duke.edu:/path/to/file /localpath/`

Copy from local to BIAC:

`scp <-r> /localpath/ <username>@hugin.biac.duke.edu:/path/to/file`

In the examples above, replace “username” with your user name, “path” with the 
full path to the desired directory on the BIAC server, “file” with the name of 
the file (including 3-character file extension), and “localpath” with the full 
path to the desired local directory. Note that the scp command has options 
for copying multiple files at once, for more info on scp, see [here](http://man7.org/linux/man-pages/man1/scp.1.html).

### Windows Users

Two additional programs will need to be installed, one that handles logging 
into the BIAC servers and another that handles file transfer.

#### Logging into the BIAC Servers

1. Download and install `X-Win32`. This can be done via Duke’s OIT     
  [site](http://oit.duke.edu/comp-print/software/index.php) 
  (Browse and Order Software).
2. Set up `X-Win32` to get to the BIAC servers. Follow the instructions [here](https://wiki.biac.duke.edu/biac:cluster:access).
3. Once X-Win is set up, select the `hugin` connection (or whatever you named 
  it) and click “Launch”. Enter your password/multi-factor authenticate when 
  prompted and you should end up with a BIAC server terminal window. If you 
  receive an “are you sure you want to connect” question, just type “yes.”

#### Copying Files from the BIAC Servers

1. Download and install `WinSCP`. This can be done from Duke’s OIT 
  [site](http://oit.duke.edu/comp-print/software/index.php) 
  (Browse and Order Software).
2. Set up `WinSCP` to get to the BIAC servers. Create a new “Site” in `WinSCP`
  (this can be called whatever you want, but “BIAC” is a good suggestion) with 
  the following values:
  
        File Protocol: SFTP
        Host name: nernst.biac.duke.edu
        Port number: 22
        User Name: (your user name)

3. Once the new site is created, highlight it and click “Login”. After 
  password/authentication prompts this should provide a graphical interface 
  for transferring files, very similar in appearance and function to Windows 
  Explorer.

### After Succesful Login

The BIAC servers run linux. You’ll need to type linux commands at the command 
prompt in order to do anything. An introduction to this environment can be 
found [here](http://linuxcommand.org/lc3_learning_the_shell.php).

The BIAC servers also have a variety of image analysis software packages 
installed. In order to use any of them, you’ll need to enter “interactive” mode 
by simply typing “qinteract” into the command line. This may prompt another 
password/authentication request. The list of installed software can be found 
[here](https://wiki.biac.duke.edu/biac:cluster:packages).



